%% Generated by lilypond-book
%% Options: [alt=[image of music],indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  #(define dump-extents #t)
  
  indent = 0\mm
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}

\layout {
  
}



% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 5

\score 
 { 
\new Staff 
<< 
\new Voice
 {

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'triangle
<c' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'triangle
<c' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'petrucci
<a' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'petrucci
<a' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'baroque
<g' >2

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'cross
<d' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'cross
<d' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'triangle
<c' >2

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'cross
<d' >2

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'cross
<d' >2

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'triangle
<c' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'triangle
<c' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'baroque
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'petrucci
<a' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'petrucci
<a' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'baroque
<g' >2

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<f' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'diamond
<e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'cross
<d' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'cross
<d' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'triangle
<c' >2

}
>>
\layout {}
\midi {
	\context {
	\Score
	tempoWholesPerMinute = #(ly:make-moment 100 4) 
}
}
}	
\version "2.12.3"



% ****************************************************************
% end ly snippet
% ****************************************************************
