%% Generated by lilypond-book
%% Options: [alt=[image of music],indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  #(define dump-extents #t)
  
  indent = 0\mm
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}

\layout {
  
}



% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 5

\score 
 { 
\new Staff 
<< 
\new Voice
 {

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'altdefault
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'baroque
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'neomensural
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'mensural
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'petrucci
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic-black
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic-mixed
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'diamond
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'cross
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'xcircle
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'triangle
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'slash
<c' >8

}
>>
\layout {}
\midi {
	\context {
	\Score
	tempoWholesPerMinute = #(ly:make-moment 100 4) 
}
}
}	
\version "2.12.3"



% ****************************************************************
% end ly snippet
% ****************************************************************
