
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 07 21:28:13 EDT 2011
//----------------------------------------------------

package compiler;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int RBRACK = 20;
  public static final int SEQUENCE = 11;
  public static final int SEMICOLON = 13;
  public static final int PLUS = 15;
  public static final int RPAREN = 18;
  public static final int DIGIT = 16;
  public static final int INSTRUMENT = 8;
  public static final int CHORD = 10;
  public static final int LBRACK = 19;
  public static final int COLOR = 6;
  public static final int LPAREN = 17;
  public static final int COLON = 14;
  public static final int ID = 3;
  public static final int NOTE = 9;
  public static final int COMMA = 12;
  public static final int EOF = 0;
  public static final int FOREACH = 25;
  public static final int GTHAN = 22;
  public static final int CHANGE_DURATION = 24;
  public static final int SHAPE = 7;
  public static final int LTHAN = 21;
  public static final int error = 1;
  public static final int ADD_TO_SEQUENCE = 23;
  public static final int ASSIGN = 5;
  public static final int DISPLAY = 26;
  public static final int NEW = 4;
  public static final int STRING_TEXT = 2;
}

