/* The following code was generated by JFlex 1.4.3 on 5/7/11 9:12 PM */

//*Jonathan*//

package compiler;

import java.io.FileReader;
import java.io.IOException;
import java_cup.runtime.*;
import java.lang.Error ;


class Utility
{
	public static void check(boolean expr)
	{
		if (false == expr)
			throw (new java.lang.Error("Error: Assertion failed."));
	}

	private static final String[] errorMessage = {
			"Error: Unmatched end-of-comment punctuation.",
			"Error: Unmatched start-of-comment punctuation.",
			"Error: Unclosed string.", "Error: Illegal character." };
	public static final int E_ENDCOMMENT = 0;
	public static final int E_STARTCOMMENT = 1;
	public static final int E_UNCLOSEDSTR = 2;
	public static final int E_UNMATCHED = 3;

	public static void error(int code)
	{
		System.out.println(errorMessage[code]);
	}
}




/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/7/11 9:12 PM from the specification file
 * <tt>/Users/Ieile/Documents/Programming/mus/src/lexer/LexicalAnalyzer.lex</tt>
 */
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int COMMENTLINE = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\1\1\13\2\0\1\1\22\0\1\1\1\0\1\11\1\4"+
    "\3\0\1\12\1\45\1\46\1\15\1\51\1\43\1\7\1\5\1\14"+
    "\12\3\1\60\1\44\1\54\1\52\1\53\2\0\2\2\1\21\1\2"+
    "\1\6\3\2\1\25\4\2\1\36\4\2\1\32\7\2\1\47\1\10"+
    "\1\50\1\55\1\4\1\0\1\34\1\2\1\41\1\37\1\17\1\42"+
    "\1\2\1\33\1\56\2\2\1\23\1\31\1\16\1\22\1\35\1\40"+
    "\1\24\1\26\1\27\1\30\1\2\1\20\1\2\1\57\1\2\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\0\1\2\1\1\1\3\1\4\1\5"+
    "\1\6\1\2\7\3\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\1"+
    "\2\2\1\23\1\4\1\0\1\5\1\24\1\6\1\25"+
    "\1\26\1\27\11\3\1\30\2\0\1\1\1\31\1\32"+
    "\1\1\1\4\1\0\1\5\1\24\1\0\1\6\1\0"+
    "\1\33\15\3\1\34\2\3\1\35\1\36\2\3\1\37"+
    "\10\3\1\40\1\41\1\3\1\42\1\3\1\43";

  private static int [] zzUnpackAction() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\61\0\142\0\223\0\223\0\304\0\365\0\u0126"+
    "\0\u0157\0\u0188\0\u01b9\0\u01ea\0\u021b\0\u024c\0\u027d\0\u02ae"+
    "\0\u02df\0\223\0\223\0\223\0\223\0\223\0\223\0\223"+
    "\0\223\0\223\0\u0310\0\223\0\223\0\u0341\0\u0372\0\u03a3"+
    "\0\223\0\u03d4\0\u0405\0\u0436\0\223\0\u0467\0\223\0\223"+
    "\0\223\0\u0498\0\u04c9\0\u04fa\0\u052b\0\u055c\0\u058d\0\u05be"+
    "\0\u05ef\0\u0620\0\223\0\u0651\0\u0682\0\u06b3\0\223\0\223"+
    "\0\u06e4\0\u0715\0\u0715\0\u0746\0\u0126\0\u0777\0\u07a8\0\u07d9"+
    "\0\304\0\u080a\0\u083b\0\u086c\0\u089d\0\u08ce\0\u08ff\0\u0930"+
    "\0\u0961\0\u0992\0\u09c3\0\u09f4\0\u0a25\0\u0a56\0\304\0\u0a87"+
    "\0\u0ab8\0\304\0\304\0\u0ae9\0\u0b1a\0\304\0\u0b4b\0\u0b7c"+
    "\0\u0bad\0\u0bde\0\u0c0f\0\u0c40\0\u0c71\0\u0ca2\0\304\0\304"+
    "\0\u0cd3\0\304\0\u0d04\0\304";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\1\6\1\7\2\4\1\6\2\4\1\10"+
    "\1\11\1\5\1\12\1\4\1\13\2\6\1\14\3\6"+
    "\1\15\4\6\1\16\3\6\1\17\1\20\2\6\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\2\6\1\35\13\36\1\5\1\37"+
    "\1\40\43\36\13\5\1\41\45\5\63\0\3\6\1\0"+
    "\1\6\7\0\25\6\13\0\2\6\4\0\1\7\1\0"+
    "\1\42\1\43\52\0\10\10\1\44\1\45\2\0\45\10"+
    "\10\11\1\46\1\0\1\47\1\0\45\11\14\0\1\50"+
    "\1\51\45\0\3\6\1\0\1\6\7\0\1\6\1\52"+
    "\23\6\13\0\2\6\3\0\3\6\1\0\1\6\7\0"+
    "\4\6\1\53\10\6\1\54\7\6\13\0\2\6\3\0"+
    "\3\6\1\0\1\6\7\0\1\55\24\6\13\0\2\6"+
    "\3\0\3\6\1\0\1\6\7\0\1\6\1\56\13\6"+
    "\1\57\7\6\13\0\2\6\3\0\3\6\1\0\1\6"+
    "\7\0\4\6\1\60\20\6\13\0\2\6\3\0\3\6"+
    "\1\0\1\6\7\0\25\6\13\0\1\61\1\6\3\0"+
    "\3\6\1\0\1\6\7\0\4\6\1\62\20\6\13\0"+
    "\2\6\55\0\1\63\4\0\13\36\1\0\1\64\1\65"+
    "\56\36\1\0\1\66\1\67\56\36\1\0\1\70\1\71"+
    "\43\36\3\0\1\42\2\0\1\43\55\0\1\72\3\0"+
    "\1\73\41\0\1\73\7\0\1\10\1\74\6\10\1\44"+
    "\1\75\1\0\1\76\45\10\1\11\1\77\6\11\1\46"+
    "\1\11\1\47\1\100\45\11\2\0\3\6\1\0\1\6"+
    "\7\0\2\6\1\101\22\6\13\0\2\6\3\0\3\6"+
    "\1\0\1\6\7\0\5\6\1\102\17\6\13\0\2\6"+
    "\3\0\3\6\1\0\1\6\7\0\4\6\1\103\20\6"+
    "\13\0\2\6\3\0\3\6\1\0\1\6\7\0\10\6"+
    "\1\104\14\6\13\0\2\6\3\0\3\6\1\0\1\6"+
    "\7\0\22\6\1\105\2\6\13\0\2\6\3\0\3\6"+
    "\1\0\1\6\7\0\16\6\1\106\6\6\13\0\2\6"+
    "\3\0\3\6\1\0\1\6\7\0\11\6\1\107\13\6"+
    "\13\0\2\6\3\0\3\6\1\0\1\6\7\0\10\6"+
    "\1\110\14\6\13\0\2\6\3\0\3\6\1\0\1\6"+
    "\7\0\6\6\1\111\16\6\13\0\2\6\1\0\13\36"+
    "\1\0\1\66\1\0\56\36\2\0\1\71\56\36\1\0"+
    "\1\66\1\65\56\36\1\0\1\64\1\71\43\36\3\0"+
    "\1\72\55\0\1\10\1\74\6\10\1\44\1\45\1\0"+
    "\1\76\45\10\1\0\1\76\6\0\1\10\2\0\1\76"+
    "\45\0\1\11\1\77\6\11\1\46\1\0\1\47\1\100"+
    "\45\11\1\0\1\100\6\0\1\11\2\0\1\100\47\0"+
    "\3\6\1\0\1\6\7\0\4\6\1\112\20\6\13\0"+
    "\2\6\3\0\3\6\1\0\1\6\7\0\6\6\1\113"+
    "\16\6\13\0\2\6\3\0\3\6\1\0\1\6\7\0"+
    "\11\6\1\114\13\6\13\0\2\6\3\0\3\6\1\0"+
    "\1\6\7\0\12\6\1\115\12\6\13\0\2\6\3\0"+
    "\3\6\1\0\1\6\7\0\17\6\1\116\5\6\13\0"+
    "\2\6\3\0\3\6\1\0\1\6\7\0\1\6\1\117"+
    "\23\6\13\0\2\6\3\0\3\6\1\0\1\6\7\0"+
    "\17\6\1\120\5\6\13\0\2\6\3\0\3\6\1\0"+
    "\1\6\7\0\1\6\1\121\23\6\13\0\2\6\3\0"+
    "\3\6\1\0\1\6\7\0\6\6\1\122\16\6\13\0"+
    "\2\6\3\0\3\6\1\0\1\6\7\0\21\6\1\123"+
    "\3\6\13\0\2\6\3\0\3\6\1\0\1\6\7\0"+
    "\6\6\1\124\16\6\13\0\2\6\3\0\3\6\1\0"+
    "\1\6\7\0\1\6\1\125\23\6\13\0\2\6\3\0"+
    "\3\6\1\0\1\6\7\0\1\6\1\126\23\6\13\0"+
    "\2\6\3\0\3\6\1\0\1\6\7\0\5\6\1\127"+
    "\17\6\13\0\2\6\3\0\3\6\1\0\1\6\7\0"+
    "\16\6\1\130\6\6\13\0\2\6\3\0\3\6\1\0"+
    "\1\6\7\0\12\6\1\131\12\6\13\0\2\6\3\0"+
    "\3\6\1\0\1\6\7\0\1\132\24\6\13\0\2\6"+
    "\3\0\3\6\1\0\1\6\7\0\16\6\1\133\6\6"+
    "\13\0\2\6\3\0\3\6\1\0\1\6\7\0\23\6"+
    "\1\134\1\6\13\0\2\6\3\0\3\6\1\0\1\6"+
    "\7\0\13\6\1\135\11\6\13\0\2\6\3\0\3\6"+
    "\1\0\1\6\7\0\23\6\1\136\1\6\13\0\2\6"+
    "\3\0\3\6\1\0\1\6\7\0\25\6\13\0\1\6"+
    "\1\137\3\0\3\6\1\0\1\6\7\0\15\6\1\140"+
    "\7\6\13\0\2\6\3\0\3\6\1\0\1\6\7\0"+
    "\1\6\1\141\23\6\13\0\2\6\3\0\3\6\1\0"+
    "\1\6\7\0\1\6\1\142\23\6\13\0\2\6\3\0"+
    "\3\6\1\0\1\6\7\0\1\143\24\6\13\0\2\6"+
    "\3\0\3\6\1\0\1\6\7\0\11\6\1\144\13\6"+
    "\13\0\2\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3381];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\0\2\11\14\1\11\11\1\1\2\11"+
    "\3\1\1\11\1\1\1\0\1\1\1\11\1\1\3\11"+
    "\11\1\1\11\2\0\1\1\2\11\2\1\1\0\2\1"+
    "\1\0\1\1\1\0\44\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[100];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private int comment_counter = 0;
  
  
  class Symbol{
  Symbol(int consti, String text, Object value, int charBegin, int charEnd){
    this.value = value;
    this.text = text;
    this.charBegin = charBegin;
    this.charEnd = charEnd;
    this.consti = consti;
  }
    
    public String toString(){
       return "Token text:" + text + ". Value is:" + value + ".";
    }

    private int charBegin, charEnd;
    String text;
    Object value ;
    int consti ;
    
    public java_cup.runtime.Symbol returnSymbol()
    {
   	 java_cup.runtime.Symbol x = new java_cup.runtime.Symbol (consti, charBegin, charEnd, value ) ;
     return x ;
    }
}
  
  


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 140) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 16: 
          { return new Symbol(ParserSym.LTHAN, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 36: break;
        case 12: 
          { return new Symbol(ParserSym.RBRACK, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 37: break;
        case 15: 
          { return new Symbol(ParserSym.GTHAN, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 38: break;
        case 26: 
          { comment_counter--;
     Utility.check(comment_counter >= 0);
     if (comment_counter == 0) yybegin(YYINITIAL);
          }
        case 39: break;
        case 29: 
          { return new Symbol(ParserSym.COLOR, yytext(), null, yychar, yychar+5).returnSymbol();
          }
        case 40: break;
        case 35: 
          { return new Symbol(ParserSym.INSTRUMENT, yytext(), null, yychar, yychar+10).returnSymbol();
          }
        case 41: break;
        case 17: 
          { return new Symbol(ParserSym.CHANGE_DURATION, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 42: break;
        case 2: 
          { System.out.println("Illegal character: <" + yytext() + ">");
	    Utility.error(Utility.E_UNMATCHED);
          }
        case 43: break;
        case 31: 
          { return new Symbol(ParserSym.SHAPE, yytext(), null, yychar, yychar+5).returnSymbol();
          }
        case 44: break;
        case 27: 
          { return new Symbol(ParserSym.NEW, yytext(), null, yychar, yychar+3).returnSymbol();
          }
        case 45: break;
        case 23: 
          { yybegin(COMMENT); comment_counter++;
          }
        case 46: break;
        case 20: 
          { String str = yytext().substring(1, yytext().length() - 1);

	Utility.check(str.length() == yytext().length() - 2);
	return (new Symbol(ParserSym.STRING_TEXT, str, str, yychar, yychar + str.length()).returnSymbol());
          }
        case 47: break;
        case 19: 
          { yybegin(YYINITIAL);
          }
        case 48: break;
        case 30: 
          { return new Symbol(ParserSym.CHORD, yytext(), null, yychar, yychar+5).returnSymbol();
          }
        case 49: break;
        case 6: 
          { String str = yytext().substring(1, yytext().length());		

        Utility.error(Utility.E_UNCLOSEDSTR);
	Utility.check(str.length() == yytext().length() - 1);
        return (new Symbol(ParserSym.STRING_TEXT, str, str, yychar, yychar + str.length()).returnSymbol());
          }
        case 50: break;
        case 9: 
          { return new Symbol(ParserSym.LPAREN, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 51: break;
        case 11: 
          { return new Symbol(ParserSym.LBRACK, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 52: break;
        case 7: 
          { return new Symbol(ParserSym.COMMA, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 53: break;
        case 4: 
          { return (new Symbol(ParserSym.DIGIT, yytext(), new Integer(yytext()), yychar, yychar + yytext().length()).returnSymbol());
          }
        case 54: break;
        case 25: 
          { comment_counter++;
          }
        case 55: break;
        case 33: 
          { return new Symbol(ParserSym.FOREACH, yytext(), null, yychar, yychar+7).returnSymbol();
          }
        case 56: break;
        case 8: 
          { return new Symbol(ParserSym.SEMICOLON, yytext(), null, yychar, yychar+4).returnSymbol();
          }
        case 57: break;
        case 18: 
          { return new Symbol(ParserSym.COLON, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 58: break;
        case 10: 
          { return new Symbol(ParserSym.RPAREN, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 59: break;
        case 28: 
          { return new Symbol(ParserSym.NOTE, yytext(), null, yychar, yychar+4).returnSymbol();
          }
        case 60: break;
        case 34: 
          { return new Symbol(ParserSym.SEQUENCE, yytext(), null, yychar, yychar+8).returnSymbol();
          }
        case 61: break;
        case 21: 
          { String str = yytext().substring(1, yytext().length() - 1);
		
       Utility.check(str.length() == yytext().length() - 2);
       return (new Symbol(ParserSym.STRING_TEXT, str, str, yychar, yychar + str.length()).returnSymbol());
          }
        case 62: break;
        case 5: 
          { String str = yytext().substring(1, yytext().length());

       Utility.error(Utility.E_UNCLOSEDSTR);
       Utility.check(str.length() == yytext().length() - 1);
       return (new Symbol(ParserSym.STRING_TEXT, str, str, yychar, yychar + str.length()).returnSymbol());
          }
        case 63: break;
        case 13: 
          { return new Symbol(ParserSym.PLUS, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 64: break;
        case 14: 
          { return new Symbol(ParserSym.ASSIGN, yytext(), null, yychar, yychar+1).returnSymbol();
          }
        case 65: break;
        case 32: 
          { return new Symbol(ParserSym.DISPLAY, yytext(), null, yychar, yychar+7).returnSymbol();
          }
        case 66: break;
        case 22: 
          { yybegin(COMMENTLINE);
          }
        case 67: break;
        case 3: 
          { return (new Symbol(ParserSym.ID, yytext(), yytext(), yychar, yychar + yytext().length()).returnSymbol());
          }
        case 68: break;
        case 24: 
          { return new Symbol(ParserSym.ADD_TO_SEQUENCE, yytext(), null, yychar, yychar+2).returnSymbol();
          }
        case 69: break;
        case 1: 
          { 
          }
        case 70: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return new java_cup.runtime.Symbol(ParserSym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
