%% Generated by lilypond-book
%% Options: [alt=[image of music],indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  #(define dump-extents #t)
  
  indent = 0\mm
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}

\layout {
  
}



% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 5

\score 
 { 
\new Staff 
<< 
\new Voice
 {

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<e' g' b' d'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<b' f'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<b' f'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'xcircle
<e' g' b' d'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic-black
<e' g' b' d'' f'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic-black
<b' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic-black
<b' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'harmonic-black
<e' g' b' d'' f'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #grey
\override NoteHead #'style = #'default
<g' b' d'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #grey
\override NoteHead #'style = #'default
<e' f'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #grey
\override NoteHead #'style = #'default
<e' f'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #grey
\override NoteHead #'style = #'default
<g' b' d'' >4

}
>>
\layout {}
\midi {
	\context {
	\Score
	tempoWholesPerMinute = #(ly:make-moment 100 4) 
}
}
}	
\version "2.12.3"



% ****************************************************************
% end ly snippet
% ****************************************************************
