%% Generated by lilypond-book
%% Options: [alt=[image of music],indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  #(define dump-extents #t)
  
  indent = 0\mm
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}

\layout {
  
}



% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 5

\score 
 { 
\new Staff 
<< 
\new Voice
 {

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #darkyellow
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #red
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #white
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #yellow
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #darkred
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #darkgreen
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #grey
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #darkblue
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #darkmagenta
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #darkcyan
\override NoteHead #'style = #'default
<c' >8

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'default
<c' >8

}
>>
\layout {}
\midi {
	\context {
	\Score
	tempoWholesPerMinute = #(ly:make-moment 100 4) 
}
}
}	
\version "2.12.3"



% ****************************************************************
% end ly snippet
% ****************************************************************
