%% Generated by lilypond-book
%% Options: [alt=[image of music],indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  #(define dump-extents #t)
  
  indent = 0\mm
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}

\layout {
  
}



% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 5

\score 
 { 
\new Staff 
<< 
\new Voice
 {

\set Staff.midiInstrument = #"fx 8 (sci-fi)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"brass section"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"sitar"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"church organ"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"synthbrass 1"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"banjo"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"reed organ"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"synthbrass 2"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"shamisen"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"accordion"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"koto"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"harmonica"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"alto sax"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"kalimba"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"concertina"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"tenor sax"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"acoustic guitar (nylon)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"baritone sax"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"fiddle"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"acoustic guitar (steel)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"oboe"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"shanai"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"electric guitar (jazz)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"english horn"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"tinkle bell"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"electric guitar (clean)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"bassoon"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"agogo"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"electric guitar (muted)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"acoustic bass"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"pan flute"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"synth drum"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"electric bass (finger)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"blown bottle"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"reverse cymbal"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"electric bass (pick)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"shakuhachi"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"guitar fret noise"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"fretless bass"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"whistle"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"breath noise"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"slap bass 1"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"ocarina"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"seashore"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"slap bass 2"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"lead 1 (square)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"bird tweet"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"synth bass 1"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"lead 2 (sawtooth)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"telephone ring"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"synth bass 2"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"lead 3 (calliope)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"helicopter"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"lead 4 (chiff)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"applause"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"viola"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"lead 5 (charang)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"gunshot"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"cello"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

\set Staff.midiInstrument = #"lead 6 (voice)"
\override NoteHead #'color = #black
\override NoteHead #'style = #'default
<c' >4

}
>>
\layout {}
\midi {
	\context {
	\Score
	tempoWholesPerMinute = #(ly:make-moment 100 4) 
}
}
}	
\version "2.12.3"



% ****************************************************************
% end ly snippet
% ****************************************************************
