%% Generated by lilypond-book
%% Options: [alt=[image of music],indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************



\paper {
  #(define dump-extents #t)
  
  indent = 0\mm
  force-assignment = #""
  line-width = #(- line-width (* mm  3.000000))
}

\layout {
  
}



% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 5

\score 
 { 
\new Staff 
<< 
\new Voice
 {

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<fis'' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<e'' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<d'' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<cis'' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<b' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<a' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<b' >2

\set Staff.midiInstrument = #"violin"
\override NoteHead #'color = #magenta
\override NoteHead #'style = #'petrucci
<cis'' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<d'' fis'' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<cis'' e'' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<b' d'' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<a' cis'' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<g' b' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<fis' a' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<g' b' >2

\set Staff.midiInstrument = #"rock organ"
\override NoteHead #'color = #blue
\override NoteHead #'style = #'xcircle
<e' cis'' >2

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<d' d'' fis'' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<fis' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<a' cis'' e'' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<g' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<fis' b' d'' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<d' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<fis' a' cis'' >4

\set Staff.midiInstrument = #"bagpipe"
\override NoteHead #'color = #cyan
\override NoteHead #'style = #'triangle
<e' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<d' g' b' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<b >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<d' fis' a' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<a' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<g' g' b' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<b' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<a' e' cis'' >4

\set Staff.midiInstrument = #"soprano sax"
\override NoteHead #'color = #red
\override NoteHead #'style = #'harmonic
<g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<fis' d' d'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<d' fis' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<e' a' cis'' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<cis'' g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<d'' fis' b >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<fis'' d' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<a'' fis' a' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<a' e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<b' d' g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<g' b >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<a' d' fis' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<fis' a' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<d' g' g' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<d'' b' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<d'' a' e' >4

\set Staff.midiInstrument = #"acoustic grand"
\override NoteHead #'color = #green
\override NoteHead #'style = #'default
<cis'' g' >4

}
>>
\layout {}
\midi {
	\context {
	\Score
	tempoWholesPerMinute = #(ly:make-moment 100 4) 
}
}
}	
\version "2.12.3"



% ****************************************************************
% end ly snippet
% ****************************************************************
